config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.3.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/RECETOX/RIAssigner:
      branch: main
      repo: https://github.com/RECETOX/RIAssigner
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Sty:
    repos:
      github.com/RECETOX/RIAssigner flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-amber-eleuth.sh
        container: qc.sty_lovely-carmine-bat
timeout: 600
